package com.tensquare.recruit.pojo;

public class TbEnterprise {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enterprise.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enterprise.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enterprise.summary
     *
     * @mbg.generated
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enterprise.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enterprise.labels
     *
     * @mbg.generated
     */
    private String labels;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enterprise.coordinate
     *
     * @mbg.generated
     */
    private String coordinate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enterprise.ishot
     *
     * @mbg.generated
     */
    private String ishot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enterprise.logo
     *
     * @mbg.generated
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enterprise.jobcount
     *
     * @mbg.generated
     */
    private Integer jobcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_enterprise.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enterprise.id
     *
     * @return the value of tb_enterprise.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enterprise.id
     *
     * @param id the value for tb_enterprise.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enterprise.name
     *
     * @return the value of tb_enterprise.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enterprise.name
     *
     * @param name the value for tb_enterprise.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enterprise.summary
     *
     * @return the value of tb_enterprise.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enterprise.summary
     *
     * @param summary the value for tb_enterprise.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enterprise.address
     *
     * @return the value of tb_enterprise.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enterprise.address
     *
     * @param address the value for tb_enterprise.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enterprise.labels
     *
     * @return the value of tb_enterprise.labels
     *
     * @mbg.generated
     */
    public String getLabels() {
        return labels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enterprise.labels
     *
     * @param labels the value for tb_enterprise.labels
     *
     * @mbg.generated
     */
    public void setLabels(String labels) {
        this.labels = labels == null ? null : labels.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enterprise.coordinate
     *
     * @return the value of tb_enterprise.coordinate
     *
     * @mbg.generated
     */
    public String getCoordinate() {
        return coordinate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enterprise.coordinate
     *
     * @param coordinate the value for tb_enterprise.coordinate
     *
     * @mbg.generated
     */
    public void setCoordinate(String coordinate) {
        this.coordinate = coordinate == null ? null : coordinate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enterprise.ishot
     *
     * @return the value of tb_enterprise.ishot
     *
     * @mbg.generated
     */
    public String getIshot() {
        return ishot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enterprise.ishot
     *
     * @param ishot the value for tb_enterprise.ishot
     *
     * @mbg.generated
     */
    public void setIshot(String ishot) {
        this.ishot = ishot == null ? null : ishot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enterprise.logo
     *
     * @return the value of tb_enterprise.logo
     *
     * @mbg.generated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enterprise.logo
     *
     * @param logo the value for tb_enterprise.logo
     *
     * @mbg.generated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enterprise.jobcount
     *
     * @return the value of tb_enterprise.jobcount
     *
     * @mbg.generated
     */
    public Integer getJobcount() {
        return jobcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enterprise.jobcount
     *
     * @param jobcount the value for tb_enterprise.jobcount
     *
     * @mbg.generated
     */
    public void setJobcount(Integer jobcount) {
        this.jobcount = jobcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_enterprise.url
     *
     * @return the value of tb_enterprise.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_enterprise.url
     *
     * @param url the value for tb_enterprise.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}