package com.tensquare.qa.pojo;

import java.util.Date;

public class TbProblem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_problem.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_problem.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_problem.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_problem.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_problem.userid
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_problem.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_problem.visits
     *
     * @mbg.generated
     */
    private Long visits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_problem.thumbup
     *
     * @mbg.generated
     */
    private Long thumbup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_problem.reply
     *
     * @mbg.generated
     */
    private Long reply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_problem.solve
     *
     * @mbg.generated
     */
    private String solve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_problem.replyname
     *
     * @mbg.generated
     */
    private String replyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_problem.replytime
     *
     * @mbg.generated
     */
    private Date replytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_problem.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_problem.id
     *
     * @return the value of tb_problem.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_problem.id
     *
     * @param id the value for tb_problem.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_problem.title
     *
     * @return the value of tb_problem.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_problem.title
     *
     * @param title the value for tb_problem.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_problem.createtime
     *
     * @return the value of tb_problem.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_problem.createtime
     *
     * @param createtime the value for tb_problem.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_problem.updatetime
     *
     * @return the value of tb_problem.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_problem.updatetime
     *
     * @param updatetime the value for tb_problem.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_problem.userid
     *
     * @return the value of tb_problem.userid
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_problem.userid
     *
     * @param userid the value for tb_problem.userid
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_problem.nickname
     *
     * @return the value of tb_problem.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_problem.nickname
     *
     * @param nickname the value for tb_problem.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_problem.visits
     *
     * @return the value of tb_problem.visits
     *
     * @mbg.generated
     */
    public Long getVisits() {
        return visits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_problem.visits
     *
     * @param visits the value for tb_problem.visits
     *
     * @mbg.generated
     */
    public void setVisits(Long visits) {
        this.visits = visits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_problem.thumbup
     *
     * @return the value of tb_problem.thumbup
     *
     * @mbg.generated
     */
    public Long getThumbup() {
        return thumbup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_problem.thumbup
     *
     * @param thumbup the value for tb_problem.thumbup
     *
     * @mbg.generated
     */
    public void setThumbup(Long thumbup) {
        this.thumbup = thumbup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_problem.reply
     *
     * @return the value of tb_problem.reply
     *
     * @mbg.generated
     */
    public Long getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_problem.reply
     *
     * @param reply the value for tb_problem.reply
     *
     * @mbg.generated
     */
    public void setReply(Long reply) {
        this.reply = reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_problem.solve
     *
     * @return the value of tb_problem.solve
     *
     * @mbg.generated
     */
    public String getSolve() {
        return solve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_problem.solve
     *
     * @param solve the value for tb_problem.solve
     *
     * @mbg.generated
     */
    public void setSolve(String solve) {
        this.solve = solve == null ? null : solve.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_problem.replyname
     *
     * @return the value of tb_problem.replyname
     *
     * @mbg.generated
     */
    public String getReplyname() {
        return replyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_problem.replyname
     *
     * @param replyname the value for tb_problem.replyname
     *
     * @mbg.generated
     */
    public void setReplyname(String replyname) {
        this.replyname = replyname == null ? null : replyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_problem.replytime
     *
     * @return the value of tb_problem.replytime
     *
     * @mbg.generated
     */
    public Date getReplytime() {
        return replytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_problem.replytime
     *
     * @param replytime the value for tb_problem.replytime
     *
     * @mbg.generated
     */
    public void setReplytime(Date replytime) {
        this.replytime = replytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_problem.content
     *
     * @return the value of tb_problem.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_problem.content
     *
     * @param content the value for tb_problem.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}