package com.tensquare.qa.pojo;

public class TbUlKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ul.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ul.lid
     *
     * @mbg.generated
     */
    private String lid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ul.uid
     *
     * @return the value of tb_ul.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ul.uid
     *
     * @param uid the value for tb_ul.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ul.lid
     *
     * @return the value of tb_ul.lid
     *
     * @mbg.generated
     */
    public String getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ul.lid
     *
     * @param lid the value for tb_ul.lid
     *
     * @mbg.generated
     */
    public void setLid(String lid) {
        this.lid = lid == null ? null : lid.trim();
    }
}