package com.tensquare.article.dao;

import com.tensquare.article.pojo.TbColumn;

public interface TbColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_column
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_column
     *
     * @mbg.generated
     */
    int insert(TbColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_column
     *
     * @mbg.generated
     */
    int insertSelective(TbColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_column
     *
     * @mbg.generated
     */
    TbColumn selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_column
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_column
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbColumn record);
}