package com.tensquare.friend.pojo;

public class TbFriendKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend.userid
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend.friendid
     *
     * @mbg.generated
     */
    private String friendid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend.userid
     *
     * @return the value of tb_friend.userid
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend.userid
     *
     * @param userid the value for tb_friend.userid
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend.friendid
     *
     * @return the value of tb_friend.friendid
     *
     * @mbg.generated
     */
    public String getFriendid() {
        return friendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend.friendid
     *
     * @param friendid the value for tb_friend.friendid
     *
     * @mbg.generated
     */
    public void setFriendid(String friendid) {
        this.friendid = friendid == null ? null : friendid.trim();
    }
}