package com.tensquare.friend.pojo;

public class TbFriend extends TbFriendKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend.islike
     *
     * @mbg.generated
     */
    private String islike;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend.islike
     *
     * @return the value of tb_friend.islike
     *
     * @mbg.generated
     */
    public String getIslike() {
        return islike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend.islike
     *
     * @param islike the value for tb_friend.islike
     *
     * @mbg.generated
     */
    public void setIslike(String islike) {
        this.islike = islike == null ? null : islike.trim();
    }
}