package com.tensquare.recruit.dao;

import com.tensquare.recruit.pojo.TbRecruit;

public interface TbRecruitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recruit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recruit
     *
     * @mbg.generated
     */
    int insert(TbRecruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recruit
     *
     * @mbg.generated
     */
    int insertSelective(TbRecruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recruit
     *
     * @mbg.generated
     */
    TbRecruit selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recruit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbRecruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recruit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbRecruit record);
}