package com.tensquare.qa.dao;

import com.tensquare.qa.pojo.TbProblem;

public interface TbProblemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_problem
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_problem
     *
     * @mbg.generated
     */
    int insert(TbProblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_problem
     *
     * @mbg.generated
     */
    int insertSelective(TbProblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_problem
     *
     * @mbg.generated
     */
    TbProblem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_problem
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbProblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_problem
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TbProblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_problem
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbProblem record);
}