package com.tensquare.qa.dao;

import com.tensquare.qa.pojo.TbReply;

public interface TbReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbg.generated
     */
    int insert(TbReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbg.generated
     */
    int insertSelective(TbReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbg.generated
     */
    TbReply selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TbReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbReply record);
}