package com.tensquare.qa.dao;

import com.tensquare.qa.pojo.TbUlKey;

public interface TbUlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ul
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TbUlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ul
     *
     * @mbg.generated
     */
    int insert(TbUlKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ul
     *
     * @mbg.generated
     */
    int insertSelective(TbUlKey record);
}