package com.tensquare.friend.dao;

import com.tensquare.friend.pojo.TbFriend;
import com.tensquare.friend.pojo.TbFriendKey;

public interface TbFriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TbFriendKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbg.generated
     */
    int insert(TbFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbg.generated
     */
    int insertSelective(TbFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbg.generated
     */
    TbFriend selectByPrimaryKey(TbFriendKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbFriend record);
}