package com.tensquare.friend.dao;

import com.tensquare.friend.pojo.TbNoFriendKey;

public interface TbNoFriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_no_friend
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TbNoFriendKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_no_friend
     *
     * @mbg.generated
     */
    int insert(TbNoFriendKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_no_friend
     *
     * @mbg.generated
     */
    int insertSelective(TbNoFriendKey record);
}