package com.tensquare.user.pojo;

import java.util.Date;

public class TbUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.regdate
     *
     * @mbg.generated
     */
    private Date regdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.updatedate
     *
     * @mbg.generated
     */
    private Date updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.lastdate
     *
     * @mbg.generated
     */
    private Date lastdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.online
     *
     * @mbg.generated
     */
    private Long online;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.interest
     *
     * @mbg.generated
     */
    private String interest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.personality
     *
     * @mbg.generated
     */
    private String personality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.fanscount
     *
     * @mbg.generated
     */
    private Integer fanscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.followcount
     *
     * @mbg.generated
     */
    private Integer followcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.id
     *
     * @return the value of tb_user.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.id
     *
     * @param id the value for tb_user.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.mobile
     *
     * @return the value of tb_user.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.mobile
     *
     * @param mobile the value for tb_user.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.password
     *
     * @return the value of tb_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.password
     *
     * @param password the value for tb_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.nickname
     *
     * @return the value of tb_user.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.nickname
     *
     * @param nickname the value for tb_user.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.sex
     *
     * @return the value of tb_user.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.sex
     *
     * @param sex the value for tb_user.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.birthday
     *
     * @return the value of tb_user.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.birthday
     *
     * @param birthday the value for tb_user.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.avatar
     *
     * @return the value of tb_user.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.avatar
     *
     * @param avatar the value for tb_user.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.email
     *
     * @return the value of tb_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.email
     *
     * @param email the value for tb_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.regdate
     *
     * @return the value of tb_user.regdate
     *
     * @mbg.generated
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.regdate
     *
     * @param regdate the value for tb_user.regdate
     *
     * @mbg.generated
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.updatedate
     *
     * @return the value of tb_user.updatedate
     *
     * @mbg.generated
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.updatedate
     *
     * @param updatedate the value for tb_user.updatedate
     *
     * @mbg.generated
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.lastdate
     *
     * @return the value of tb_user.lastdate
     *
     * @mbg.generated
     */
    public Date getLastdate() {
        return lastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.lastdate
     *
     * @param lastdate the value for tb_user.lastdate
     *
     * @mbg.generated
     */
    public void setLastdate(Date lastdate) {
        this.lastdate = lastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.online
     *
     * @return the value of tb_user.online
     *
     * @mbg.generated
     */
    public Long getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.online
     *
     * @param online the value for tb_user.online
     *
     * @mbg.generated
     */
    public void setOnline(Long online) {
        this.online = online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.interest
     *
     * @return the value of tb_user.interest
     *
     * @mbg.generated
     */
    public String getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.interest
     *
     * @param interest the value for tb_user.interest
     *
     * @mbg.generated
     */
    public void setInterest(String interest) {
        this.interest = interest == null ? null : interest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.personality
     *
     * @return the value of tb_user.personality
     *
     * @mbg.generated
     */
    public String getPersonality() {
        return personality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.personality
     *
     * @param personality the value for tb_user.personality
     *
     * @mbg.generated
     */
    public void setPersonality(String personality) {
        this.personality = personality == null ? null : personality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.fanscount
     *
     * @return the value of tb_user.fanscount
     *
     * @mbg.generated
     */
    public Integer getFanscount() {
        return fanscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.fanscount
     *
     * @param fanscount the value for tb_user.fanscount
     *
     * @mbg.generated
     */
    public void setFanscount(Integer fanscount) {
        this.fanscount = fanscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.followcount
     *
     * @return the value of tb_user.followcount
     *
     * @mbg.generated
     */
    public Integer getFollowcount() {
        return followcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.followcount
     *
     * @param followcount the value for tb_user.followcount
     *
     * @mbg.generated
     */
    public void setFollowcount(Integer followcount) {
        this.followcount = followcount;
    }
}