server:
  port: 9007
  servlet:
    context-path: /guass

spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      database: spitdb
      host: 47.111.191.26
      port: 27017

  devtools:
    restart:
      enabled: true  #设置开启热部署

logging:
  config: classpath:logback-spring.xml
  level:
    com.tensquare.base.dao: DEBUG


#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true



